version: 2

sources:
  - name: bigquery_source
    schema: raw

    tables:
      - name: orders
models:
    - name: raw_orders
      description: " orders trasnformed table"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null